# -*- coding: utf-8 -*-
"""py for gen AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGWVoBh6dInXEqHNMQ2xd5eWoCiWksqs
"""

#variable is a container to store information and retrieve it later.

x = 10

_mycity = "solan"
_mycity

#rules for naming variable
#starting position of variable are undersore or letter
my_sub = "Python"
my_sub

my_sub = "Python"
print(my_sub)

my_sub1="Maths"
my_sub1

my@sub="machine learning"
my@sub

my_sub="Machine learning"
MY_SUB="deep learning"

import keyword
print(keyword.kwlist)

x=10
type(x)

y=3.14
type(y)

x="Solan"
type(x)

x=True
type(x)

e=None
type(e)

my_sub="mahcine learning"
print(my_sub)

my_sub="machine learning"
len(my_sub)

my_sub="machine learning"
my_sub[-1]

my_sub="machine learning"
# Example of slicing: [start_index:end_index:step]
# To get 'machine'
print(my_sub[0:7])
# To get 'learning'
print(my_sub[8:])
# To get every other character
print(my_sub[::2])

my_sub="machine learning"
my_sub[0:2:4]

my_sub="malyalam"
my_sub.count('a')

my_sub=[32,45,67,87]
my_sub[3]

my_list=[2,5,67,89,34,67,33,30]
my_list[0:5:-1]

my_list

my_list=[23,45,44,3,66]
sorted(my_list,reverse=True)

my_list.append(100)
my_list

my_dict={"name":"rit","food":"alooparantha"}
type(my_dict)

my_dict={"name":"rit","food":"alooparantha"}
my_dict["food"]

my_dict.update({"age":20})
my_dict

state_list=["hp","up","mp"]
my_list=[23,45,44,3,66]
dict(zip(state_list,my_list))

list(zip(state_list,my_list))

age=int(input("Enter your age:"))
if age>=24:
  print("you should marry now!!!!")
elif age<23:
  print("teri nahi hogi")
else:
  print("shut the fuck up")

my_sub="python"
for i in my_sub:
  print(i)

for i in range (0,6):
  print(i)



my_list=[90,85,33,66]
for i in my_list:
  (print(i))

i=0
while i<5:
  print(i)
  i+=1

"""#rules for naming variable
#starting position of variable are undersore or letter
my_sub = "Python"
my_sub
#remaining part of variable are letter , unerscore or number
# for variable naming we can not use number on first position
#variable doesnot contain space or symbol
#python is case sensitive,for variable names such as my_sub, MY_SUB are different
#keywords are reserved words in python
#data type
#numeric
#integers are nos except decimal figures
#floating point number are decimals
#string is data in the form of text
#boolean is used to store values in the form of true or false statements that too capital letter
#none is used to define null value which means nothing
"""

i=0
while i<5:
  i+=1
  if i ==3:
    break
  else:
      print(i)

i=0
while i<5:
  i+=1
  if i ==3:
    continue
  else:
      print(i)

i=0
while i<5:
  i+=1
  if i ==3:
    pass
    print(i)
  else:
      print(i)

list1=[23,45,67]
list2=[34,67,85]
list2.extend(list1)
list2

#user defined functions without argument
def add():
  a= int(input("enter the first number:"))
  b= int(input("enter the second number:"))
  return a+b
  print(add())

print(add())

#positinal argument
def Calculation(a, b):
  print("addition:", a+b)
  print("subtraction:", a-b)
  print("multiplication:", a*b)
  print("division:", a/b)
  return " Calculation is complete"

print(Calculation(10,5))

#default argument
def area_perimeter(width=8, height=3):
   area=width*height
   perimeter=2*(width+height)
   return "area of rectangle is ", area ,"and perimeter is " perimeter

print(area_perimeter(2))

print(interest(r=8,t=4,p=300))

#nonkeyword variable length argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

test(1,2,3,4,5,6,9)

def sum_num(*args):
  sum=0
  for i in args:
    sum+=i
  return sum

sum_num(1,2,3,4,5)

#keyword variable length argument
def test(**kwargs):
  print(kwargs)
  print(len(kwargs))
  print(type(kwargs))

test(a=10, b=40, c=33, d= 26)

#keyword argument
def interest (p,r,t):
   i=(p*r*t)/100
   return i

list2.pop()

list2

list2.reverse()
list2